{{- if and .Values.grafanaAnnotation.enabled (not .Values.grafanaAnnotation.existingSecret) .Values.grafanaAnnotation.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuo.fullname" . }}-grafana-annotation
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuo.labels" . | nindent 4 }}
  {{- with .Values.grafanaAnnotation.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.grafanaAnnotation.existingSecretKey }}: {{ .Values.grafanaAnnotation.apiToken | quote }}
{{- end }}
