yarnPath: .yarn/releases/yarn-4.12.0.cjs

# Use node_modules instead of PnP (Backstage requirement)
nodeLinker: node-modules

# Use project-local cache (avoid permission issues in containers)
enableGlobalCache: false
cacheFolder: .yarn/cache
