{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ahen.fullname" . }}-events
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ahen.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
{{- end }}
