{{- if not .Values.slack.existingSecret -}}
{{- if not .Values.slack.webhookUrl }}
{{- fail "slack.webhookUrl is required when slack.existingSecret is empty" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-slack" (include "ahen.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ahen.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhook-url: {{ .Values.slack.webhookUrl | quote }}
{{- end }}
