apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensearch-conflict-viewer.fullname" . }}
  labels:
    {{- include "opensearch-conflict-viewer.labels" . | nindent 4 }}
data:
  OPENSEARCH_URL: {{ required "config.opensearchUrl is required" .Values.config.opensearchUrl | quote }}
  INDEX_TARGETS: {{ .Values.config.indexTargets | quote }}
  KIBANA_INDEX: {{ .Values.config.kibanaIndex | quote }}
  REFRESH_INTERVAL: {{ .Values.config.refreshInterval | quote }}
  CLUSTER_NAME: {{ .Values.config.clusterName | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
