{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch-conflict-viewer.fullname" . }}
  labels:
    {{- include "opensearch-conflict-viewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  selector:
    {{- include "opensearch-conflict-viewer.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
{{- end }}
