{{- range .Values.ec2Schedules }}
---
apiVersion: ec2-scheduler.io/v1alpha1
kind: EC2Schedule
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "default" }}
  labels:
    {{- include "ec2-scheduler.labels" $ | nindent 4 }}
spec:
  region: {{ .spec.region }}
  {{- with .spec.timezone }}
  timezone: {{ . }}
  {{- end }}
  instanceSelector:
    {{- toYaml .spec.instanceSelector | nindent 4 }}
  schedules:
    {{- toYaml .spec.schedules | nindent 4 }}
  {{- with .spec.paused }}
  paused: {{ . }}
  {{- end }}
  {{- with .spec.dryRun }}
  dryRun: {{ . }}
  {{- end }}
  {{- with .spec.assumeRoleArn }}
  assumeRoleArn: {{ . }}
  {{- end }}
{{- end }}
