//! File-based configuration for ij.
//!
//! Loads and saves YAML configuration from `$XDG_CONFIG_HOME/ij/config.yaml`
//! (defaults to `~/.config/ij/config.yaml`).

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};

/// File-based configuration.
/// Default AWS CLI config file path.
const DEFAULT_AWS_CONFIG_FILE: &str = "~/.aws/config";

fn default_aws_config_file() -> String {
    DEFAULT_AWS_CONFIG_FILE.to_string()
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileConfig {
    /// Default AWS profile name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aws_profile: Option<String>,

    /// AWS CLI config file path.
    #[serde(default = "default_aws_config_file")]
    pub aws_config_file: String,

    /// Regions to scan (empty = all 22 regions).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub scan_regions: Vec<String>,

    /// Default tag filters (Key=Value format).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tag_filters: Vec<String>,

    /// Only show running instances.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub running_only: Option<bool>,

    /// Log level (trace, debug, info, warn, error).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_level: Option<String>,
}

impl Default for FileConfig {
    fn default() -> Self {
        Self {
            aws_profile: None,
            aws_config_file: default_aws_config_file(),
            scan_regions: Vec::new(),
            tag_filters: Vec::new(),
            running_only: None,
            log_level: None,
        }
    }
}

impl FileConfig {
    /// Return default config file path.
    ///
    /// Uses `$XDG_CONFIG_HOME/ij/config.yaml`, falling back to `~/.config/ij/config.yaml`.
    pub fn default_path() -> Result<PathBuf> {
        let base = match std::env::var("XDG_CONFIG_HOME") {
            Ok(xdg) if !xdg.is_empty() => PathBuf::from(xdg),
            _ => dirs::home_dir()
                .ok_or_else(|| Error::Config("could not determine home directory".into()))?
                .join(".config"),
        };
        Ok(base.join("ij").join("config.yaml"))
    }

    /// Load config from the default path. Returns `Ok(None)` if the file does not exist.
    pub fn load_default() -> Result<Option<Self>> {
        let path = Self::default_path()?;
        if !path.exists() {
            return Ok(None);
        }
        Self::load(&path).map(Some)
    }

    /// Load config from a specific path.
    pub fn load(path: &PathBuf) -> Result<Self> {
        let contents = std::fs::read_to_string(path)?;
        let config: FileConfig = serde_yaml::from_str(&contents)?;
        Ok(config)
    }

    /// Save config to the default path.
    pub fn save_default(&self) -> Result<PathBuf> {
        let path = Self::default_path()?;
        self.save(&path)?;
        Ok(path)
    }

    /// Save config to a specific path, creating parent directories as needed.
    pub fn save(&self, path: &PathBuf) -> Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let yaml = serde_yaml::to_string(self)?;
        let content = format!("# ij configuration file\n# Generated by `ij init`\n{yaml}");
        std::fs::write(path, content)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn default_has_expected_values() {
        let fc = FileConfig::default();
        assert_eq!(fc.aws_profile, None);
        assert_eq!(fc.aws_config_file, "~/.aws/config");
        assert!(fc.scan_regions.is_empty());
        assert!(fc.tag_filters.is_empty());
        assert_eq!(fc.running_only, None);
        assert_eq!(fc.log_level, None);
    }

    #[test]
    fn serialize_full_config() {
        let fc = FileConfig {
            aws_profile: Some("prod".into()),
            aws_config_file: "/custom/aws/config".into(),
            scan_regions: vec!["us-east-1".into(), "ap-northeast-2".into()],
            tag_filters: vec!["Environment=production".into()],
            running_only: Some(true),
            log_level: Some("debug".into()),
        };
        let yaml = serde_yaml::to_string(&fc).unwrap();
        assert!(yaml.contains("aws_profile: prod"));
        assert!(yaml.contains("aws_config_file: /custom/aws/config"));
        assert!(yaml.contains("us-east-1"));
        assert!(yaml.contains("ap-northeast-2"));
        assert!(yaml.contains("Environment=production"));
        assert!(yaml.contains("running_only: true"));
        assert!(yaml.contains("log_level: debug"));
    }

    #[test]
    fn serialize_default_omits_optional_fields() {
        let fc = FileConfig::default();
        let yaml = serde_yaml::to_string(&fc).unwrap();
        // aws_config_file is always present
        assert!(yaml.contains("aws_config_file:"));
        // Optional None fields are skipped
        assert!(!yaml.contains("aws_profile:"));
        assert!(!yaml.contains("running_only:"));
        assert!(!yaml.contains("log_level:"));
        // Empty vecs are skipped
        assert!(!yaml.contains("scan_regions:"));
        assert!(!yaml.contains("tag_filters:"));
    }

    #[test]
    fn deserialize_full_yaml() {
        let yaml = r#"
aws_profile: dev
aws_config_file: /tmp/aws-config
scan_regions:
  - us-west-2
tag_filters:
  - Team=platform
running_only: false
log_level: warn
"#;
        let fc: FileConfig = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(fc.aws_profile.as_deref(), Some("dev"));
        assert_eq!(fc.aws_config_file, "/tmp/aws-config");
        assert_eq!(fc.scan_regions, vec!["us-west-2"]);
        assert_eq!(fc.tag_filters, vec!["Team=platform"]);
        assert_eq!(fc.running_only, Some(false));
        assert_eq!(fc.log_level.as_deref(), Some("warn"));
    }

    #[test]
    fn deserialize_empty_yaml_uses_defaults() {
        let yaml = "{}";
        let fc: FileConfig = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(fc.aws_profile, None);
        assert_eq!(fc.aws_config_file, "~/.aws/config");
        assert!(fc.scan_regions.is_empty());
        assert!(fc.tag_filters.is_empty());
        assert_eq!(fc.running_only, None);
        assert_eq!(fc.log_level, None);
    }

    #[test]
    fn deserialize_partial_yaml() {
        let yaml = "aws_profile: staging\n";
        let fc: FileConfig = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(fc.aws_profile.as_deref(), Some("staging"));
        assert_eq!(fc.aws_config_file, "~/.aws/config");
        assert!(fc.scan_regions.is_empty());
    }

    #[test]
    fn roundtrip_save_and_load() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.yaml");

        let original = FileConfig {
            aws_profile: Some("test-profile".into()),
            aws_config_file: "/opt/aws/config".into(),
            scan_regions: vec!["eu-west-1".into()],
            tag_filters: vec!["Env=test".into()],
            running_only: Some(false),
            log_level: Some("trace".into()),
        };
        original.save(&path).unwrap();

        let loaded = FileConfig::load(&path).unwrap();
        assert_eq!(loaded.aws_profile, original.aws_profile);
        assert_eq!(loaded.aws_config_file, original.aws_config_file);
        assert_eq!(loaded.scan_regions, original.scan_regions);
        assert_eq!(loaded.tag_filters, original.tag_filters);
        assert_eq!(loaded.running_only, original.running_only);
        assert_eq!(loaded.log_level, original.log_level);
    }

    #[test]
    fn save_creates_parent_directories() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("nested").join("dir").join("config.yaml");

        let fc = FileConfig::default();
        fc.save(&path).unwrap();
        assert!(path.exists());
    }

    #[test]
    fn save_includes_comment_header() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.yaml");

        FileConfig::default().save(&path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("# ij configuration file\n# Generated by `ij init`\n"));
    }

    #[test]
    fn load_nonexistent_file_returns_io_error() {
        let path = PathBuf::from("/tmp/ij-test-nonexistent-12345/config.yaml");
        let result = FileConfig::load(&path);
        assert!(result.is_err());
    }

    #[test]
    fn load_invalid_yaml_returns_config_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad.yaml");
        let mut f = std::fs::File::create(&path).unwrap();
        writeln!(f, "{{{{invalid yaml").unwrap();

        let result = FileConfig::load(&path);
        assert!(result.is_err());
    }
}
