apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurora-database-insights-exporter.fullname" . }}
  labels:
    {{- include "aurora-database-insights-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "aurora-database-insights-exporter.selectorLabels" . | nindent 4 }}
