{{- if and .Values.auth.createSecret (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snowflake-exporter.secretName" . }}
  labels:
    {{- include "snowflake-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.tokenSecretKey }}: {{ required "auth.token is required when auth.createSecret is true" .Values.auth.token | quote }}
{{- end }}
