apiVersion: v2
name: kuo
description: Kubernetes Upgrade Operator for EKS clusters
type: application
deprecated: false
version: 0.4.0
appVersion: "0.3.0"
home: https://github.com/younsl/o
sources:
  - https://github.com/younsl/o/tree/main/box/kubernetes/kubernetes-upgrade-operator
maintainers:
  - name: younsl
    email: cysl@kakao.com
    url: https://github.com/younsl
keywords:
  - eks
  - kubernetes
  - upgrade
  - operator
  - aws
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Set default pod priorityClassName to system-cluster-critical to protect the operator from preemption"
    - kind: added
      description: "Set default deployment revisionHistoryLimit to 5"
