{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.scraper.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "trivy-collector.scraperName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-collector.scraperSelectorLabels" . | nindent 4 }}
    {{- with .Values.scraper.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.scraper.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "trivy-collector.scraperSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.scraper.serviceMonitor.interval }}
      {{- with .Values.scraper.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
