import { useEffect, useState } from "react";
import { Link, Navigate, useNavigate, useParams } from "react-router-dom";
import { api, ArtifactList, AuditLogList, humanSize, repoEndpoint, Repository } from "../api";
import { UpstreamStatus } from "../components/UpstreamStatus";
import { ConfirmModal } from "../components/ConfirmModal";
import { Select } from "../components/Select";
import { MemberList } from "./RepositoryNew";
import { ApprovalList, VersionDenies } from "./Approvals";

const TABS = [
  { key: "artifacts", label: "Artifacts" },
  { key: "audit", label: "Audit" },
  { key: "settings", label: "Settings" },
];

export function RepositoryDetail() {
  const { id, tab = "artifacts" } = useParams();
  const [repo, setRepo] = useState<Repository | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    api.getRepository(Number(id)).then(setRepo).catch((e) => setError(e.message));
  }, [id]);

  if (!repo) return <div>{error || "Loading…"}</div>;

  // The Approvals tab exists for every proxy repo: version denies apply even
  // when the approval workflow is off, while the approval queue itself only
  // renders with the policy enabled.
  const gated = repo.type === "proxy" && Boolean(repo.config.approval?.enabled);
  const tabs = repo.type === "proxy"
    ? [...TABS.slice(0, 2), { key: "approvals", label: "Approvals" }, ...TABS.slice(2)]
    : TABS;

  if (!tabs.some((t) => t.key === tab)) {
    return <Navigate to={`/repositories/${id}/artifacts`} replace />;
  }

  const endpoint = repoEndpoint(repo.format, repo.name);

  return (
    <>
      <h1>{repo.name} <span className={`badge ${repo.type}`}>{repo.type}</span> <span className="badge">{repo.format}</span></h1>

      <div className="panel">
        <h2>Client endpoint (forklift) <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· read-only</span></h2>
        <div className="inline">
          <code className="code-field" title="Generated by forklift (read-only)">{endpoint.url}</code>
          <button className="btn secondary" type="button"
            onClick={() => navigator.clipboard?.writeText(endpoint.url)}>Copy</button>
        </div>
        {endpoint.hint && <p className="muted" style={{ marginTop: 8 }}>Configure in: {endpoint.hint}</p>}
      </div>

      <nav className="tabs">
        {tabs.map((t) => (
          <Link key={t.key} className={`tab ${tab === t.key ? "active" : ""}`}
            to={`/repositories/${id}/${t.key}`}>{t.label}</Link>
        ))}
      </nav>

      {tab === "artifacts" && <Artifacts repoId={repo.id} />}
      {tab === "audit" && <AuditLogs repoId={repo.id} />}
      {tab === "approvals" && repo.type === "proxy" && (
        <>
          {gated && <ApprovalList repo={repo.name} showRepo={false} />}
          <VersionDenies repo={repo.name} showRepo={false} repoNames={[repo.name]} />
        </>
      )}
      {tab === "settings" && <Settings repo={repo} setRepo={setRepo} />}
    </>
  );
}

function Settings({ repo, setRepo }: { repo: Repository; setRepo: (r: Repository) => void }) {
  const navigate = useNavigate();
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);

  const save = async () => {
    setError("");
    setSaved(false);
    try {
      await api.updateRepository(repo.id, { upstream_url: repo.upstream_url, config: repo.config });
      setSaved(true);
    } catch (e) {
      setError((e as Error).message);
    }
  };

  const del = async () => {
    await api.deleteRepository(repo.id);
    navigate("/repositories");
  };

  const cache = repo.config.cache;
  const age = repo.config.age_policy;
  // Older repos may predate the approval config section.
  const approval = repo.config.approval ?? { enabled: false, mode: "enforce", auto_approve: [] };

  return (
    <>
      <ConfirmModal
        open={confirmDelete}
        title={`Delete repository "${repo.name}"?`}
        message="This removes the repository and its cached/hosted artifacts. This cannot be undone."
        confirmLabel="Delete"
        danger
        onConfirm={del}
        onCancel={() => setConfirmDelete(false)}
      />

      {(repo.type === "proxy" || repo.type === "group") && (
        <h2 className="section-title">Repository</h2>
      )}

      {repo.type === "proxy" && (
        <div className="panel">
          <div className="inline" style={{ justifyContent: "space-between" }}>
            <h2 style={{ margin: 0 }}>Upstream</h2>
            <UpstreamStatus repoId={repo.id} withButton />
          </div>
          <input style={{ marginTop: 12 }} value={repo.upstream_url}
            onChange={(e) => setRepo({ ...repo, upstream_url: e.target.value })} />
        </div>
      )}

      {repo.type === "group" && <GroupMembers repo={repo} setRepo={setRepo} />}

      {repo.type === "proxy" && (
        <div className="panel">
          <h2>Cache</h2>
          <div className="checkbox">
            <input type="checkbox" checked={cache.enabled}
              onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, enabled: e.target.checked } } })} />
            <span>Enable caching</span>
          </div>
          <div className="row">
            <div><label>Metadata TTL</label>
              <input value={cache.metadata_ttl}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, metadata_ttl: e.target.value } } })} /></div>
            <div><label>Negative TTL</label>
              <input value={cache.negative_ttl}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, negative_ttl: e.target.value } } })} /></div>
            <div><label>Max size (bytes, 0 = unlimited)</label>
              <input type="number" value={cache.max_size_bytes}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, max_size_bytes: Number(e.target.value) } } })} /></div>
          </div>
        </div>
      )}

      {repo.type === "proxy" && (
        <h2 className="section-title">Security <span className="muted">· supply-chain policies</span></h2>
      )}

      {repo.type === "proxy" && (
        <div className="panel">
          <h2>Age policy</h2>
          <div className="checkbox">
            <input type="checkbox" checked={age.enabled}
              onChange={(e) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, enabled: e.target.checked } } })} />
            <span>Enable supply-chain cooldown</span>
          </div>
          <div className="row">
            <div><label>Min age (e.g. 3d)</label>
              <input value={age.min_age}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, min_age: e.target.value } } })} /></div>
            <div><label>Action</label>
              <Select value={age.action}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, action: v } } })}
                options={[
                  { value: "block", label: "block" },
                  { value: "warn", label: "warn" },
                ]} /></div>
          </div>
        </div>
      )}

      {repo.type === "proxy" && (
        <div className="panel">
          <h2>Package approval <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· quarantine</span></h2>
          <div className="checkbox">
            <input type="checkbox" checked={approval.enabled}
              onChange={(e) => setRepo({ ...repo, config: { ...repo.config, approval: { ...approval, enabled: e.target.checked } } })} />
            <span>Require approval before serving a package</span>
          </div>
          <div className="row">
            <div><label>Mode</label>
              <Select value={approval.mode || "enforce"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, approval: { ...approval, mode: v } } })}
                options={[
                  { value: "enforce", label: "enforce (block unapproved)" },
                  { value: "audit", label: "audit (serve, log only)" },
                ]} /></div>
            <div><label>Auto-approve patterns (one per line)</label>
              <textarea rows={3} style={{ width: "100%" }}
                value={(approval.auto_approve ?? []).join("\n")}
                placeholder={"@company/*"}
                onChange={(e) => setRepo({
                  ...repo,
                  config: {
                    ...repo.config,
                    approval: { ...approval, auto_approve: e.target.value.split("\n").map((s) => s.trim()).filter(Boolean) },
                  },
                })} /></div>
          </div>
          <p className="muted">Approval admits whole packages; version freshness is still gated by the age policy.</p>
        </div>
      )}

      {error && <div className="error">{error}</div>}
      {saved && <div className="muted">Saved.</div>}
      {repo.type !== "hosted" && <button className="btn" onClick={save}>Save changes</button>}

      <div className="panel danger" style={{ marginTop: 18 }}>
        <h2 style={{ marginTop: 0 }}>Danger zone</h2>
        <p className="muted">Deleting a repository removes its cached/hosted artifacts. This cannot be undone.</p>
        <button className="btn danger" onClick={() => setConfirmDelete(true)}>Delete repository</button>
      </div>
    </>
  );
}

// GroupMembers edits a group repository's ordered member list. Changes apply
// on Save like the other settings panels.
function GroupMembers({ repo, setRepo }: { repo: Repository; setRepo: (r: Repository) => void }) {
  const [repos, setRepos] = useState<Repository[]>([]);
  useEffect(() => {
    api.listRepositories().then(setRepos).catch(() => setRepos([]));
  }, []);

  const members = repo.config.group?.members ?? [];
  const setMembers = (m: string[]) =>
    setRepo({ ...repo, config: { ...repo.config, group: { members: m } } });
  const candidates = repos.filter(
    (r) => r.format === repo.format && r.type !== "group" && r.name !== repo.name && !members.includes(r.name),
  );

  return (
    <div className="panel">
      <h2>Members <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· lookup order, first hit wins</span></h2>
      <MemberList members={members} onChange={setMembers}
        repoIndex={Object.fromEntries(repos.map((r) => [r.name, r.id]))} />
      <div className="inline" style={{ marginTop: 8 }}>
        <Select value="" placeholder="add member…"
          onChange={(v) => v && setMembers([...members, v])}
          options={candidates.map((r) => ({ value: r.name, label: `${r.name} (${r.type})` }))} />
      </div>
    </div>
  );
}

function Artifacts({ repoId }: { repoId: number }) {
  const [data, setData] = useState<ArtifactList | null>(null);
  const [prefix, setPrefix] = useState("");
  const [error, setError] = useState("");

  const load = (p = prefix) =>
    api.listArtifacts(repoId, p).then(setData).catch((e) => setError(e.message));
  useEffect(() => { load(""); /* eslint-disable-next-line */ }, [repoId]);

  return (
    <div className="panel">
      <div className="inline" style={{ justifyContent: "space-between" }}>
        <h2 style={{ margin: 0 }}>Artifacts</h2>
        {data && <span className="muted">{data.count} items · {humanSize(data.total_size)}</span>}
      </div>
      <form className="inline" style={{ marginTop: 12 }} onSubmit={(e) => { e.preventDefault(); load(); }}>
        <input placeholder="Filter by path prefix (e.g. com/acme or @scope/pkg)"
          value={prefix} onChange={(e) => setPrefix(e.target.value)} />
        <button className="btn secondary" type="submit">Filter</button>
      </form>
      {error && <div className="error">{error}</div>}
      <table style={{ marginTop: 12 }}>
        <thead>
          <tr><th>Path</th><th>Version</th><th>Size</th><th>Type</th><th>Last accessed</th></tr>
        </thead>
        <tbody>
          {data?.artifacts.map((a) => (
            <tr key={a.path}>
              <td style={{ fontFamily: "ui-monospace, monospace", fontSize: 12 }}>{a.path}</td>
              <td>{a.version || "—"}</td>
              <td className="muted">{humanSize(a.size)}</td>
              <td className="muted">{a.content_type}</td>
              <td className="muted">{a.last_accessed_at?.slice(0, 19).replace("T", " ")}</td>
            </tr>
          ))}
          {data && data.artifacts.length === 0 && (
            <tr><td colSpan={5} className="muted">No cached artifacts yet. Pull through the endpoint above to populate the cache.</td></tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

const AUDIT_EVENTS = ["", "download", "upload", "delete", "repo.create", "repo.update", "repo.delete",
  "approval.request", "approval.approve", "approval.reject"];
const AUDIT_PAGE_SIZE = 50;

function AuditLogs({ repoId }: { repoId: number }) {
  const [data, setData] = useState<AuditLogList | null>(null);
  const [event, setEvent] = useState("");
  const [offset, setOffset] = useState(0);
  const [error, setError] = useState("");

  useEffect(() => {
    api.listAuditLogs(repoId, event, AUDIT_PAGE_SIZE, offset)
      .then(setData).catch((e) => setError(e.message));
  }, [repoId, event, offset]);

  const refresh = () =>
    api.listAuditLogs(repoId, event, AUDIT_PAGE_SIZE, offset)
      .then(setData).catch((e) => setError(e.message));

  return (
    <div className="panel">
      <div className="inline" style={{ justifyContent: "space-between" }}>
        <h2 style={{ margin: 0 }}>Audit log</h2>
        {data && <span className="muted">{data.count} events</span>}
      </div>
      <div className="inline" style={{ marginTop: 12 }}>
        <Select value={event} onChange={(v) => { setEvent(v); setOffset(0); }}
          options={AUDIT_EVENTS.map((ev) => ({ value: ev, label: ev || "all events" }))} />
        <button className="btn secondary" type="button" onClick={refresh}>Refresh</button>
      </div>
      {error && <div className="error">{error}</div>}
      <table style={{ marginTop: 12 }}>
        <thead>
          <tr><th>Time</th><th>Event</th><th>Path</th><th>User</th><th>Status</th><th>Client IP</th></tr>
        </thead>
        <tbody>
          {data?.logs.map((l) => (
            <tr key={l.id}>
              <td className="muted">{l.created_at?.slice(0, 19).replace("T", " ")}</td>
              <td><span className="badge">{l.event}</span></td>
              <td style={{ fontFamily: "ui-monospace, monospace", fontSize: 12 }}>{l.path || "-"}</td>
              <td>{l.username || <span className="muted">anonymous</span>}</td>
              <td className={l.status >= 400 ? "error" : "muted"}>{l.status}</td>
              <td className="muted">{l.client_ip}</td>
            </tr>
          ))}
          {data && data.logs.length === 0 && (
            <tr><td colSpan={6} className="muted">No audit events recorded yet.</td></tr>
          )}
        </tbody>
      </table>
      {data && data.count > AUDIT_PAGE_SIZE && (
        <div className="inline" style={{ marginTop: 12 }}>
          <button className="btn secondary" type="button" disabled={offset === 0}
            onClick={() => setOffset(Math.max(0, offset - AUDIT_PAGE_SIZE))}>Newer</button>
          <button className="btn secondary" type="button" disabled={offset + AUDIT_PAGE_SIZE >= data.count}
            onClick={() => setOffset(offset + AUDIT_PAGE_SIZE)}>Older</button>
          <span className="muted">{offset + 1}–{Math.min(offset + AUDIT_PAGE_SIZE, data.count)} of {data.count}</span>
        </div>
      )}
    </div>
  );
}
