import { useEffect, useState } from "react";
import { Link, Navigate, useNavigate, useParams } from "react-router-dom";
import { api, Artifact, ArtifactList, AuditLogList, humanSize, Me, RepoPermission, RepoToken, repoEndpoint, Repository } from "../api";
import { UpstreamStatus } from "../components/UpstreamStatus";
import { ConfirmModal } from "../components/ConfirmModal";
import { Select } from "../components/Select";
import { Toggle } from "../components/Toggle";
import { MemberList } from "./RepositoryNew";
import { ApprovalList, SeverityBar, VersionDenies } from "./Approvals";

export function RepositoryDetail({ me }: { me: Me }) {
  const { id, tab = "artifacts" } = useParams();
  const [repo, setRepo] = useState<Repository | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    api.getRepository(Number(id)).then(setRepo).catch((e) => setError(e.message));
  }, [id]);

  if (!repo) return <div>{error || "Loading…"}</div>;

  // Tabs follow Nexus-style privileges: every authenticated reader can browse
  // Artifacts; Approvals needs the approve action; Permissions, Audit and
  // Settings are for admins and auditors (auditors see them read-only). Direct
  // URL access to a hidden tab redirects to Artifacts.
  const gated = repo.type === "proxy" && Boolean(repo.config.approval?.enabled);
  const canApprove = me.admin || me.approver;
  const canAdminView = me.admin || me.auditor;
  const tabs = [
    { key: "artifacts", label: "Artifacts" },
    ...(repo.type === "proxy" && canApprove ? [{ key: "approvals", label: "Approvals" }] : []),
    ...(canAdminView ? [{ key: "permissions", label: "Permissions" }, { key: "audit", label: "Audit" }, { key: "settings", label: "Settings" }] : []),
  ];

  if (!tabs.some((t) => t.key === tab)) {
    return <Navigate to={`/repositories/${id}/artifacts`} replace />;
  }

  const endpoint = repoEndpoint(repo.format, repo.name);

  return (
    <>
      <h1>{repo.name} <span className={`badge ${repo.type}`}>{repo.type}</span> <span className="badge">{repo.format}</span></h1>

      <div className="panel">
        <h2>Client endpoint (forklift) <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· read-only</span></h2>
        <div className="inline">
          <code className="code-field" title="Generated by forklift (read-only)">{endpoint.url}</code>
          <button className="btn secondary" type="button"
            onClick={() => navigator.clipboard?.writeText(endpoint.url)}>Copy</button>
        </div>
        {endpoint.hint && <p className="muted" style={{ marginTop: 8 }}>Configure in: {endpoint.hint}</p>}
      </div>

      <nav className="tabs">
        {tabs.map((t) => (
          <Link key={t.key} className={`tab ${tab === t.key ? "active" : ""}`}
            to={`/repositories/${id}/${t.key}`}>{t.label}</Link>
        ))}
      </nav>

      {tab === "artifacts" && <Artifacts repoId={repo.id} canDelete={!!me.admin} />}
      {tab === "permissions" && <RepoPermissions repoId={repo.id} />}
      {tab === "audit" && <AuditLogs repoId={repo.id} />}
      {tab === "approvals" && repo.type === "proxy" && (
        <>
          {gated && <ApprovalList repo={repo.name} showRepo={false} repoNames={[repo.name]} />}
          <VersionDenies repo={repo.name} showRepo={false} repoNames={[repo.name]} />
        </>
      )}
      {tab === "settings" && <Settings repo={repo} setRepo={setRepo} canWrite={!!me.admin} />}
    </>
  );
}

function Settings({ repo, setRepo, canWrite }: { repo: Repository; setRepo: (r: Repository) => void; canWrite: boolean }) {
  const navigate = useNavigate();
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [confirmPurge, setConfirmPurge] = useState(false);
  const [purged, setPurged] = useState<number | null>(null);

  const purge = async () => {
    setError("");
    setPurged(null);
    try {
      const { deleted } = await api.purgeArtifacts(repo.id);
      setConfirmPurge(false);
      setPurged(deleted);
    } catch (e) {
      setError((e as Error).message);
      setConfirmPurge(false);
    }
  };

  const save = async () => {
    setError("");
    setSaved(false);
    try {
      await api.updateRepository(repo.id, { upstream_url: repo.upstream_url, config: repo.config });
      setSaved(true);
    } catch (e) {
      setError((e as Error).message);
    }
  };

  const del = async () => {
    await api.deleteRepository(repo.id);
    navigate("/repositories");
  };

  const cache = repo.config.cache;
  const age = repo.config.age_policy;
  // Older repos may predate the approval config section.
  const approval = repo.config.approval ?? { enabled: false, mode: "enforce", auto_approve: [] };
  const vuln = repo.config.vuln ?? { enabled: false, action: "audit", threshold: "high", ignore: [] };

  return (
    <>
      {!canWrite && (
        <p className="muted" style={{ marginTop: 0 }}>
          Read-only view. You can review the configuration but not change it.
        </p>
      )}
      <ConfirmModal
        open={confirmDelete}
        title={`Delete repository "${repo.name}"?`}
        message="This removes the repository and its cached/hosted artifacts. This cannot be undone."
        confirmLabel="Delete"
        danger
        onConfirm={del}
        onCancel={() => setConfirmDelete(false)}
      />

      {/* For an auditor (canWrite=false) the whole settings form is disabled via
          fieldset[disabled], which blocks every control (mouse and keyboard);
          they can read the configuration but not change it. */}
      <fieldset className="settings-fields" disabled={!canWrite}>
      <div className="panel">
        <h2>State</h2>
        <p className="muted">
          {repo.disabled
            ? "This repository is offline: uploads and downloads are refused (503). Its config and artifacts are kept."
            : "This repository is online and serving the package protocols."}
        </p>
        {canWrite ? (
          <Toggle
            checked={!repo.disabled}
            label={repo.disabled ? "Offline" : "Online"}
            onChange={(online) => {
              setError("");
              api.setRepositoryDisabled(repo.id, !online).then(setRepo).catch((e) => setError((e as Error).message));
            }}
          />
        ) : (
          <span className={`badge ${repo.disabled ? "" : ""}`}>{repo.disabled ? "Offline" : "Online"}</span>
        )}
      </div>

      {(repo.type === "proxy" || repo.type === "group") && (
        <h2 className="section-title">Repository</h2>
      )}

      {repo.type === "proxy" && (
        <div className="panel">
          <div className="inline" style={{ justifyContent: "space-between" }}>
            <h2 style={{ marginBottom: 0 }}>Upstream</h2>
            <UpstreamStatus repoId={repo.id} withButton />
          </div>
          <input style={{ marginTop: 12 }} value={repo.upstream_url}
            onChange={(e) => setRepo({ ...repo, upstream_url: e.target.value })} />
        </div>
      )}

      {repo.type === "group" && <GroupMembers repo={repo} setRepo={setRepo} />}

      {repo.type === "proxy" && (
        <div className="panel">
          <h2>Cache</h2>
          <div className="checkbox">
            <input type="checkbox" checked={cache.enabled}
              onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, enabled: e.target.checked } } })} />
            <span>Enable caching</span>
          </div>
          <div className="row">
            <div><label>Metadata TTL</label>
              <input value={cache.metadata_ttl}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, metadata_ttl: e.target.value } } })} /></div>
            <div><label>Negative TTL</label>
              <input value={cache.negative_ttl}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, negative_ttl: e.target.value } } })} /></div>
            <div><label>Max size (bytes, 0 = unlimited)</label>
              <input type="number" value={cache.max_size_bytes}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, cache: { ...cache, max_size_bytes: Number(e.target.value) } } })} /></div>
          </div>
        </div>
      )}

      {repo.type === "proxy" && (
        <h2 className="section-title">Security <span className="muted">· supply-chain policies</span></h2>
      )}

      {repo.type === "proxy" && (
        <div className="panel">
          <h2>Age policy</h2>
          <div className="checkbox">
            <input type="checkbox" checked={age.enabled}
              onChange={(e) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, enabled: e.target.checked } } })} />
            <span>Enable supply-chain cooldown</span>
          </div>
          <div className="row">
            <div><label>Min age (e.g. 3d)</label>
              <input value={age.min_age}
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, min_age: e.target.value } } })} /></div>
            <div><label>Action</label>
              <Select value={age.action}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, age_policy: { ...age, action: v } } })}
                options={[
                  { value: "block", label: "block" },
                  { value: "warn", label: "warn" },
                ]} /></div>
          </div>
        </div>
      )}

      {repo.type === "proxy" && (
        <div className="panel">
          <h2>Package approval <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· quarantine</span></h2>
          <div className="checkbox">
            <input type="checkbox" checked={approval.enabled}
              onChange={(e) => setRepo({ ...repo, config: { ...repo.config, approval: { ...approval, enabled: e.target.checked } } })} />
            <span>Require approval before serving a package</span>
          </div>
          <div className="row">
            <div><label>Mode</label>
              <Select value={approval.mode || "enforce"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, approval: { ...approval, mode: v } } })}
                options={[
                  { value: "enforce", label: "enforce (block unapproved)" },
                  { value: "audit", label: "audit (serve, log only)" },
                ]} /></div>
            <div><label>Auto-approve patterns (one per line)</label>
              <textarea rows={3} style={{ width: "100%" }}
                value={(approval.auto_approve ?? []).join("\n")}
                placeholder={"@company/*"}
                onChange={(e) => setRepo({
                  ...repo,
                  config: {
                    ...repo.config,
                    approval: { ...approval, auto_approve: e.target.value.split("\n").map((s) => s.trim()).filter(Boolean) },
                  },
                })} /></div>
          </div>
          <p className="muted">Approval admits whole packages; version freshness is still gated by the age policy.</p>
        </div>
      )}

      {repo.type === "proxy" && (
        <div className="panel">
          <h2>Vulnerability policy <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· OSV scan</span></h2>
          <div className="checkbox">
            <input type="checkbox" checked={vuln.enabled}
              onChange={(e) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, enabled: e.target.checked } } })} />
            <span>Gate packages by known vulnerabilities</span>
          </div>
          <div className="row">
            <div><label>Threshold</label>
              <Select value={vuln.threshold || "high"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, threshold: v } } })}
                options={[
                  { value: "critical", label: "critical" },
                  { value: "high", label: "high" },
                  { value: "medium", label: "medium" },
                  { value: "low", label: "low" },
                ]} /></div>
            <div><label>Action</label>
              <Select value={vuln.action || "audit"}
                onChange={(v) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, action: v } } })}
                options={[
                  { value: "block", label: "block (refuse to serve)" },
                  { value: "warn", label: "warn (serve, log)" },
                  { value: "audit", label: "audit (serve, log)" },
                ]} /></div>
          </div>
          <label>Ignore advisories (CVE/GHSA/OSV, one per line)</label>
          <textarea rows={3} style={{ width: "100%" }}
            value={(vuln.ignore ?? []).join("\n")}
            placeholder={"CVE-2026-1234"}
            onChange={(e) => setRepo({
              ...repo,
              config: {
                ...repo.config,
                vuln: { ...vuln, ignore: e.target.value.split("\n").map((s) => s.trim()).filter(Boolean) },
              },
            })} />
          <div className="checkbox" style={{ marginTop: 8 }}>
            <input type="checkbox" checked={!!vuln.block_unscanned}
              onChange={(e) => setRepo({ ...repo, config: { ...repo.config, vuln: { ...vuln, block_unscanned: e.target.checked } } })} />
            <span>Block versions not yet scanned (block action only)</span>
          </div>
          <p className="muted">Coordinate match against OSV (direct dependency only); transitive deps and artifact integrity are out of scope. Newly disclosed advisories surface on the next re-scan.</p>
        </div>
      )}

      {repo.type !== "group" && (
        <div className="panel">
          <h2>Artifact Retention <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· idle auto-delete</span></h2>
          <div className="row">
            <div><label>Idle TTL (e.g. 7d, 2w, 0 = keep forever)</label>
              <input value={repo.config.retention?.idle_ttl ?? ""}
                placeholder="0"
                onChange={(e) => setRepo({ ...repo, config: { ...repo.config, retention: { idle_ttl: e.target.value } } })} /></div>
          </div>
          <p className="muted">Artifacts not served for this long are deleted automatically; each removal is recorded in the audit log. Based on last-served time.</p>
        </div>
      )}

      </fieldset>

      {error && <div className="error">{error}</div>}
      {saved && <div className="muted">Saved.</div>}
      {canWrite && repo.type !== "group" && <button className="btn" onClick={save}>Save changes</button>}

      {canWrite && (
      <>
      <ConfirmModal
        open={confirmPurge}
        title={`Purge all artifacts in "${repo.name}"?`}
        message="This removes every cached or hosted artifact in the repository. The repository and its settings stay. A proxy will re-cache on demand; hosted uploads cannot be recovered."
        confirmLabel="Purge artifacts"
        danger
        onConfirm={purge}
        onCancel={() => setConfirmPurge(false)}
      />

      <div className="panel danger" style={{ marginTop: 18 }}>
        <h2>Danger zone</h2>
        {repo.type !== "group" && (
          <>
            <p className="muted">Purging removes all cached/hosted artifacts but keeps the repository and its settings. This cannot be undone.</p>
            {purged !== null && <div className="muted">Purged {purged} {purged === 1 ? "artifact" : "artifacts"}.</div>}
            <button className="btn danger" onClick={() => setConfirmPurge(true)}>Purge all artifacts</button>
            <hr style={{ margin: "18px 0", border: "none", borderTop: "1px solid var(--border, #333)" }} />
          </>
        )}
        <p className="muted">Deleting a repository removes its cached/hosted artifacts. This cannot be undone.</p>
        <button className="btn danger" onClick={() => setConfirmDelete(true)}>Delete repository</button>
      </div>
      </>
      )}
    </>
  );
}

// GroupMembers edits a group repository's ordered member list. Changes apply
// on Save like the other settings panels.
function GroupMembers({ repo, setRepo }: { repo: Repository; setRepo: (r: Repository) => void }) {
  const [repos, setRepos] = useState<Repository[]>([]);
  useEffect(() => {
    api.listRepositories().then(setRepos).catch(() => setRepos([]));
  }, []);

  const members = repo.config.group?.members ?? [];
  const setMembers = (m: string[]) =>
    setRepo({ ...repo, config: { ...repo.config, group: { members: m } } });
  const candidates = repos.filter(
    (r) => r.format === repo.format && r.type !== "group" && r.name !== repo.name && !members.includes(r.name),
  );

  return (
    <div className="panel">
      <h2>Members <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· lookup order, first hit wins</span></h2>
      <MemberList members={members} onChange={setMembers}
        repoIndex={Object.fromEntries(repos.map((r) => [r.name, r.id]))}
        repoTypes={Object.fromEntries(repos.map((r) => [r.name, r.type]))} />
      <div className="inline" style={{ marginTop: 8 }}>
        <Select value="" placeholder="add member…"
          onChange={(v) => v && setMembers([...members, v])}
          options={candidates.map((r) => ({ value: r.name, label: `${r.name} (${r.type})` }))} />
      </div>
    </div>
  );
}

// RepoPermissions lists, at a glance, which roles grant access to this
// repository (every role permission whose pattern matches the repo name),
// read-only. Admin-only tab. Assignment itself is managed on the Roles pages.
function RepoPermissions({ repoId }: { repoId: number }) {
  const [perms, setPerms] = useState<RepoPermission[] | null>(null);
  const [tokens, setTokens] = useState<RepoToken[] | null>(null);
  const [error, setError] = useState("");
  useEffect(() => {
    api.repositoryPermissions(repoId).then(setPerms).catch((e) => setError((e as Error).message));
    api.repositoryTokens(repoId).then(setTokens).catch((e) => setError((e as Error).message));
  }, [repoId]);

  return (
    <>
      <div className="panel">
        <h2>
          Roles <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· granting access to this repository</span>
        </h2>
        {error && <div className="error">{error}</div>}
        {!perms ? <div className="muted">Loading…</div> : perms.length === 0 ? (
          <p className="muted">No role grants access to this repository. Add a permission on a role (Roles page) whose pattern matches this repository.</p>
        ) : (
          <table>
            <thead>
              <tr><th>Role</th><th>Matched pattern</th><th>Actions</th><th>Users</th></tr>
            </thead>
            <tbody>
              {perms.map((p, i) => (
                <tr key={`${p.role_id}-${i}`}>
                  <td><Link to={`/roles/${p.role_id}`}>{p.role}</Link></td>
                  <td style={{ fontFamily: "ui-monospace, monospace", fontSize: 13 }}>{p.repo_pattern}</td>
                  <td>
                    <div className="inline" style={{ flexWrap: "wrap", gap: 6 }}>
                      {p.actions.map((a) => <span key={a} className="badge">{a}</span>)}
                    </div>
                  </td>
                  <td>{p.user_count}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      <div className="panel">
        <h2>
          Access tokens <span className="muted" style={{ fontWeight: 400, fontSize: 12 }}>· reaching this repository</span>
        </h2>
        {!tokens ? <div className="muted">Loading…</div> : tokens.length === 0 ? (
          <p className="muted">No access token reaches this repository.</p>
        ) : (
          <table>
            <thead>
              <tr><th>Token</th><th>Owner</th><th>Scope</th><th>Actions</th><th>Expires</th></tr>
            </thead>
            <tbody>
              {tokens.map((t) => (
                <tr key={t.token_id}>
                  <td>{t.name}</td>
                  <td>{t.owner || <span className="muted">unknown</span>}</td>
                  <td style={{ fontFamily: "ui-monospace, monospace", fontSize: 13 }}>
                    {t.unscoped
                      ? <span className="muted" title="Unscoped token: inherits the owner's role access to every repository.">unscoped (inherits roles)</span>
                      : t.repo_pattern}
                  </td>
                  <td>
                    <div className="inline" style={{ flexWrap: "wrap", gap: 6 }}>
                      {t.unscoped
                        ? <span className="muted">per owner roles</span>
                        : t.actions.map((a) => <span key={a} className="badge">{a}</span>)}
                    </div>
                  </td>
                  <td className="muted">{t.expires_at ? new Date(t.expires_at).toLocaleDateString() : "never"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </>
  );
}

function Artifacts({ repoId, canDelete }: { repoId: number; canDelete: boolean }) {
  const [data, setData] = useState<ArtifactList | null>(null);
  const [prefix, setPrefix] = useState("");
  const [error, setError] = useState("");
  const [deleting, setDeleting] = useState<Artifact | null>(null);

  const load = (p = prefix) =>
    api.listArtifacts(repoId, p).then(setData).catch((e) => setError(e.message));
  useEffect(() => { load(""); /* eslint-disable-next-line */ }, [repoId]);

  const del = async (a: Artifact) => {
    setError("");
    try {
      await api.deleteArtifact(repoId, a.path);
      setDeleting(null);
      load();
    } catch (e) {
      setError((e as Error).message);
      setDeleting(null);
    }
  };

  return (
    <div className="panel">
      <div className="inline" style={{ justifyContent: "space-between" }}>
        <h2 style={{ marginBottom: 0 }}>Artifacts</h2>
        {data && <span className="muted">{data.count} items · {humanSize(data.total_size)}</span>}
      </div>
      <form className="inline" style={{ marginTop: 12 }} onSubmit={(e) => { e.preventDefault(); load(); }}>
        <input placeholder="Filter by path prefix (e.g. com/acme or @scope/pkg)"
          value={prefix} onChange={(e) => setPrefix(e.target.value)} />
        <button className="btn secondary" type="submit">Filter</button>
      </form>
      {error && <div className="error">{error}</div>}
      <table style={{ marginTop: 12 }}>
        <thead>
          <tr><th>Path</th><th>Version</th><th>Vuln</th><th>Size</th><th>Type</th><th>Last accessed</th>{canDelete && <th></th>}</tr>
        </thead>
        <tbody>
          {data?.artifacts.map((a) => (
            <tr key={a.path}>
              <td style={{ fontFamily: "ui-monospace, monospace", fontSize: 12, wordBreak: "break-all" }}>{a.path}</td>
              <td>{a.version || "—"}</td>
              <td><SeverityBar severity={a.max_severity} counts={a.vuln_counts} source={a.vuln_source} scannedAt={a.vuln_scanned_at} /></td>
              <td className="muted">{humanSize(a.size)}</td>
              <td className="muted">{a.content_type}</td>
              <td className="muted">{a.last_accessed_at?.slice(0, 19).replace("T", " ")}</td>
              {canDelete && (
                <td style={{ textAlign: "right" }}>
                  <button className="btn secondary" onClick={() => setDeleting(a)}>Delete</button>
                </td>
              )}
            </tr>
          ))}
          {data && data.artifacts.length === 0 && (
            <tr><td colSpan={canDelete ? 7 : 6} className="muted">No cached artifacts yet. Pull through the endpoint above to populate the cache.</td></tr>
          )}
        </tbody>
      </table>
      <ConfirmModal
        open={deleting !== null}
        title="Delete artifact"
        message={deleting
          ? `${deleting.path} will be removed from this repository. A proxy can re-cache it on the next request; a hosted upload cannot be recovered.`
          : undefined}
        confirmLabel="Delete"
        danger
        onConfirm={() => deleting && del(deleting)}
        onCancel={() => setDeleting(null)}
      />
    </div>
  );
}

const AUDIT_EVENTS = ["", "download", "upload", "delete", "ttl.expire", "repo.create", "repo.update", "repo.delete",
  "approval.request", "approval.approve", "approval.reject"];
const AUDIT_PAGE_SIZE = 50;

function AuditLogs({ repoId }: { repoId: number }) {
  const [data, setData] = useState<AuditLogList | null>(null);
  const [event, setEvent] = useState("");
  const [offset, setOffset] = useState(0);
  const [error, setError] = useState("");

  useEffect(() => {
    api.listAuditLogs(repoId, event, AUDIT_PAGE_SIZE, offset)
      .then(setData).catch((e) => setError(e.message));
  }, [repoId, event, offset]);

  const refresh = () =>
    api.listAuditLogs(repoId, event, AUDIT_PAGE_SIZE, offset)
      .then(setData).catch((e) => setError(e.message));

  return (
    <div className="panel">
      <div className="inline" style={{ justifyContent: "space-between" }}>
        <h2 style={{ marginBottom: 0 }}>Audit log</h2>
        {data && <span className="muted">{data.count} events</span>}
      </div>
      <div className="inline" style={{ marginTop: 12 }}>
        <Select value={event} onChange={(v) => { setEvent(v); setOffset(0); }}
          options={AUDIT_EVENTS.map((ev) => ({ value: ev, label: ev || "all events" }))} />
        <button className="btn secondary" type="button" onClick={refresh}>Refresh</button>
      </div>
      {error && <div className="error">{error}</div>}
      <table style={{ marginTop: 12 }}>
        <thead>
          <tr><th>Time</th><th>Event</th><th>Path</th><th>User</th><th>Status</th><th>Client IP</th></tr>
        </thead>
        <tbody>
          {data?.logs.map((l) => (
            <tr key={l.id}>
              <td className="muted">{l.created_at?.slice(0, 19).replace("T", " ")}</td>
              <td><span className="badge">{l.event}</span></td>
              <td style={{ fontFamily: "ui-monospace, monospace", fontSize: 12, wordBreak: "break-all" }}>{l.path || "-"}</td>
              <td>{l.username || <span className="muted">anonymous</span>}</td>
              <td className={l.status >= 400 ? "status-err" : "muted"}>{l.status}</td>
              <td className="muted">{l.client_ip}</td>
            </tr>
          ))}
          {data && data.logs.length === 0 && (
            <tr><td colSpan={6} className="muted">No audit events recorded yet.</td></tr>
          )}
        </tbody>
      </table>
      {data && data.count > AUDIT_PAGE_SIZE && (
        <div className="inline" style={{ marginTop: 12 }}>
          <button className="btn secondary" type="button" disabled={offset === 0}
            onClick={() => setOffset(Math.max(0, offset - AUDIT_PAGE_SIZE))}>Newer</button>
          <button className="btn secondary" type="button" disabled={offset + AUDIT_PAGE_SIZE >= data.count}
            onClick={() => setOffset(offset + AUDIT_PAGE_SIZE)}>Older</button>
          <span className="muted">{offset + 1}–{Math.min(offset + AUDIT_PAGE_SIZE, data.count)} of {data.count}</span>
        </div>
      )}
    </div>
  );
}
