{{- range $policyKey, $policyValue := .Values.validatingAdmissionPolicies }}
{{- if $policyValue.enabled }}
{{- $policyName := include "kubernetes-native-policies.policyName" (dict "key" $policyKey "value" $policyValue) }}
{{- range $bindingKey, $bindingValue := $policyValue.bindings }}
{{- if $bindingValue.enabled }}
---
apiVersion: {{ $.Values.apiVersions.validatingAdmissionPolicy }}
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "kubernetes-native-policies.bindingName" (dict "policyName" $policyName "key" $bindingKey "value" $bindingValue) }}
  labels:
    {{- include "kubernetes-native-policies.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  policyName: {{ $policyName }}
  {{- with $bindingValue.validationActions }}
  validationActions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $bindingValue.matchResources }}
  matchResources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $bindingValue.paramRef }}
  paramRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
