{{- if and .Values.config.grafanaAnnotation.enabled (not .Values.config.grafanaAnnotation.existingSecret) .Values.config.grafanaAnnotation.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-ebs-autoresizer.fullname" . }}-grafana-annotation
  labels:
    {{- include "external-ebs-autoresizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.grafanaAnnotation.existingSecretKey }}: {{ .Values.config.grafanaAnnotation.apiToken | quote }}
{{- end }}
