{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-ebs-autoresizer.fullname" . }}
  labels:
    {{- include "external-ebs-autoresizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  selector:
    {{- include "external-ebs-autoresizer.selectorLabels" . | nindent 4 }}
  ports:
    - name: health
      port: {{ .Values.ports.health }}
      targetPort: health
      protocol: TCP
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
{{- end }}
